### ISSUE TITLE
Drop table lock/timeout

### ISSUE THREAD

**Issue by ErikZigo** [keboola/db-writer-pgsql#17]
Writer logs all queries instead of `drop table` query

**Comment by odinuv** [comment]
idea: 
https://github.com/keboola/db-writer-pgsql/pull/18

**Comment by odinuv** [comment]
or maybe during connection set `lock_timeout` https://www.postgresql.org/docs/9.3/static/runtime-config-client.html and if the query timeouts, handle and retry it after a while ?

**Comment by odinuv** [comment]
or set `SET statement_timeout = 10000;` and let the DROP statement timeout
https://keboola.slack.com/archives/C31U6BGJC/p1521111655000508

**Comment by ErikZigo** [comment]
Me se libi ten prvni napad s tim checkem zamku.

**Comment by ErikZigo** [comment]
Fixnuto ve 1.2.1
