### ISSUE TITLE
Test SSH tunnel

### ISSUE THREAD

**Issue by MiroCillik** [keboola/db-writer-pgsql#2]
Add tests for SSH tunnel

**Comment by ErikZigo** [comment]
https://github.com/keboola/db-writer-mysql/blob/master/tests/Keboola/DbWriter/Writer/MySQLSSHTest.php

**Comment by MiroCillik** [comment]
FIXED in https://github.com/keboola/db-writer-pgsql/commit/f135c0fe10b1f4190afc091662d6bcb8770ed3be
