### ISSUE TITLE
Developer portal icon

### ISSUE THREAD

**Issue by ErikZigo** [keboola/db-writer-pgsql#20]
Vsiml jsem si ze EX a WR maji v developer portalu zaregistrovany jiny vzhled ikony. Bylo by fajn to sjednotit. Tyka se to jen male ikony

![image](https://user-images.githubusercontent.com/1726727/40615611-c5474098-6287-11e8-9342-107fa1f15788.png)
![image](https://user-images.githubusercontent.com/1726727/40615654-ed332860-6287-11e8-9dee-d49ce08a9dfa.png)

**Comment by ujovlado** [comment]
![screenshot_2018-09-21_15-49-01](https://user-images.githubusercontent.com/419849/45885111-e005b200-bdb5-11e8-98f0-0371ea40fd9f.png)
