### ISSUE TITLE
Nahrada pgloaderu

### ISSUE THREAD

**Issue by ErikZigo** [keboola/db-writer-pgsql#24]
Chtel bych nahradit pgloader klasickym `\COPY` commandem v Postgresu.

Za posledni rok jsem na pgloaderu spalil hromadu casu a kazdym novym problemem se ukazuje ze debugovat to je peklo.

V ZD ticketu 8802 se to dostalo do stavu, kdy se spusti pgloader a hned skonci, aniz by zalogoval jakoukoliv chybu. Navic job skonci jako success, protoze pgloader skonci exitcodem `0`.

**Comment by ErikZigo** [comment]
Koukal jsem se do DB extractoru, tam se pouziva `psql` z comand liny a volani query `\COPY` (https://www.postgresql.org/docs/9.2/static/app-psql.html#APP-PSQL-META-COMMANDS-COPY)

https://github.com/keboola/db-extractor-pgsql/blob/ce4b8be3d0fe8a7d68f57ac324e5b8f0bcead5ba/src/Keboola/DbExtractor/Extractor/PgSQL.php#L164

**Comment by ErikZigo** [comment]
Dneska jsem si s tim hral a tvari se ze to je pouzitelny.

```
PGPASSWORD={DB_PASSWORD} psql \
    -h {DB_HOST} \
    -p {DB_PORT} \
    -U {DB_USER} \
    -d {DB_DATABASE} \
    -w \
    -c '\COPY {TABLE_NAME} ({COLUMNS_LIST}) FROM '\''{CSV_FILE}'\'' WITH (FORMAT CSV, HEADER TRUE, DELIMITER '\'','\'', QUOTE '\''"'\'', NULL '\'''\'');'
```

 Projistotu bych to vydal jako novy writer.

**Comment by ErikZigo** [comment]
Jediny problem na ktery jsem zatim narazil jsou prazdne hodnoty.

Kdyz mam tabulku:
```sql
CREATE TABLE "nullTest" ("id" integer, "someNumber" integer);
```

A zdrojova data v CSV:
```csv
"id","someNumber"
"123","456"
"789",""
```

Skonci import chybou:
```
ERROR:  invalid input syntax for integer: ""
CONTEXT:  COPY nullTest, line 3, column someNumber: ""
```

**Comment by ErikZigo** [comment]
Podle dokumentace lze sice nastavit retezec, ktery se pri importu prevede na `NULL`.
Problem je ale v tom ze to funguje jen za situace kdy ten retezec neni qutovany.

Tzn:
``` WITH (FORMAT CSV, HEADER TRUE, DELIMITER '\'','\'', QUOTE '\''"'\'', NULL '\'''\'')```
```csv
"id","someNumber"
"123","456"
"789",
```

``` WITH (FORMAT CSV, HEADER TRUE, DELIMITER '\'','\'', QUOTE '\''"'\'', NULL '\''\N'\'')```
```csv
"id","someNumber"
"123","456"
"789",\N
```

``` WITH (FORMAT CSV, HEADER TRUE, DELIMITER '\'','\'', QUOTE '\''"'\'', NULL '\''{CUSTOM_STRING_AS_NULL}'\'')```
```csv
"id","someNumber"
"123","456"
"789",{CUSTOM_STRING_AS_NULL}
```

To vsechno projde, ale tohle skonci chybou `ERROR:  CSV quote character must not appear in the NULL specification`:
``` WITH (FORMAT CSV, HEADER TRUE, DELIMITER '\'','\'', QUOTE '\''"'\'', NULL '\''""'\'')```
```csv
"id","someNumber"
"123","456"
"789",""
```

**Comment by ErikZigo** [comment]
Jedina moznost je pred samotnym importem projit to CSV a nahradit `""` :-/

**Comment by MiroCillik** [comment]
@ErikZigo Este to prosim vyskusaj, s tabulkou, ktora ma nenullovy sloupec typu varchar. 
Lebo si mylsim, ze je OK, ked to hodi chybu pri stlpci typu integer, do ktoreho chces nahrat prazdny string. Ale do varcharu by to prazdny string malo povolit.
Tak ci tak sa asi tomu nahradzovaniu v CSV nevyhneme. Ale nebal by som sa toho, bude to len pri stlpcoch, ktore su NULL.

Pripadne to skusit vyriesit staging tabulkou! Tzn nahrat to `\copy` commandom do staging tabulky, kde su vsetky stlpce typu varchar (ak to nebude hadzat chybu). A potom podla definicie cielovej tabulky sa prislusne stlpce pretypuju na NULL.

**Comment by ErikZigo** [comment]
@MiroCillik To mas koukam nejak podobne udelany v MSSQL writeru

**Comment by MiroCillik** [comment]
@ErikZigo jj, presne https://github.com/keboola/db-writer-mssql/blob/master/src/Writer/MSSQL.php#L106

**Comment by MiroCillik** [comment]
Bolo by ale super sa toho PgLoaderu zas zbavit :)
